services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - 1998:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin      
      KC_HEALTH_ENABLED: true
    volumes:
      - ./aruna/tests/realm.json:/opt/keycloak/data/import/realm.json
    command: "start-dev --import-realm"
    healthcheck:
      # I hate keycloak
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 5s
      timeout: 5s
      retries: 30
  jaeger:
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686 
      - 4317:4317 
      - 4318:4318
    image: jaegertracing/all-in-one:1.70.0
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_DOMAIN: minio:9000
    command: "server /data --console-address ':9001'"
  aruna:
    image: aruna:latest
    network_mode: "host"
    environment:
      REALM_KEY: |-
        -----BEGIN PRIVATE KEY-----
        MFECAQEwBQYDK2VwBCIEIJucl73sk/By4tUQqsv1qopNy1Bi+EWhPugOxB+dyFRW
        gSEAtOYxE8jy2F90OEGr7NixCoc6pDIHMG2GwhKWfJqMGQA=
        -----END PRIVATE KEY-----
      P2P_KEY: "358ea489d2f7d91466eff6edbb7d69b507346dc199d963915138865c03ffe1db"
      P2P_ADDRESS: "0.0.0.0"
      P2P_PORT: 1230
      ISSUERS: |
          [
            {
              "issuer_name": "http://localhost:1998/realms/test",
              "pubkey_url": "http://localhost:1998/realms/test/protocol/openid-connect/certs",
              "aud": ["test", "test-long"]
            }
          ]
      VARIANT: "LMDB"
      DB_PATH: "/database"
      BACKEND_TYPE: "s3"
      BACKEND_ENCRYPTION: false
      BACKEND_COMPRESSION: false
      BACKEND_DEDUPLICATION: false
      BACKEND_ACCESS_ENDPOINT: "http://localhost:9000"
      BACKEND_ACCESS_REGION: "eu-central-1"
      BACKEND_ACCESS_REGION_DISABLE_CONFIG_LOAD: true
      BACKEND_ACCESS_BUCKET: "aruna"
      BACKEND_ACCESS_ACCESS_KEY_ID: "minioadmin"
      BACKEND_ACCESS_SECRET_ACCESS_KEY: "minioadmin"
      OPENAPI_ADDRESS: "0.0.0.0"
      OPENAPI_PORT: 8080
      S3_SERVER: "0.0.0.0:1337"
      S3_HOSTNAME: "localhost:1337"
      S3_CORS_EXCEPTION: "http://localhost:3000"
      OTEL_SERVER: "http://localhost:4317"
      OTEL_SERVICE_NAME: "aruna"
    depends_on:
      keycloak:
        condition: service_healthy
