[package]
name = "data_proxy"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = {workspace = true}
anyhow = {workspace = true}
aruna-rust-api = {workspace = true}
async-channel = {workspace = true}
async-stream = "0.3.5"
async-trait = {workspace = true}
aws-config =  {workspace = true}
aws-sdk-s3 =  {workspace = true}
aws-smithy-http = "0.62.1"
base64 = {workspace = true}
byteorder = "1.5.0"
bytes = "1.10.1"
cel-interpreter = {workspace = true}
cel-parser = {workspace = true}
chrono = {workspace = true}
console-subscriber = "0.4.1"
crossbeam-skiplist = "0.1.3"
curve25519-dalek = "4.1.3"
dashmap = {workspace = true}
deadpool-postgres = {workspace = true}
diesel-ulid = {workspace = true}
digest = "0.10.7"
dotenvy = {workspace = true}
ed25519-dalek = { version = "2.1.1", features = ["pem"]}
futures = {workspace = true}
futures-channel = "0.3.30"
futures-core = "0.3.30"
futures-util = "0.3.30"
hex = {workspace = true}
hmac = {workspace = true}
http = "1.3.1"
hyper = {version = "1.6.0", features = ["full"]}
jsonwebtoken = {workspace = true}
lazy_static = {workspace = true}
md-5 = "0.10.6"
mime_guess = "2.0.5"
nom = "7.1.3"
pithos_lib = "0.6.1"
postgres-from-row = {workspace = true}
postgres-types = {workspace = true}
postgres_array = "0.11.1"
prost-wkt-types = {workspace = true}
rand = {workspace = true}
regex = "1.11.0"
reqsign = "0.16.0"
reqwest = {workspace = true}
s3s = "0.10.0"
serde = {workspace = true}
serde_json = {workspace = true}
sha2 = {workspace = true}
time = {workspace = true}
tokio = {workspace = true}
tokio-postgres = {workspace = true}
tokio-stream = {workspace = true}
toml = "0.8.22"
tonic = {workspace = true}
tower = {workspace = true}
tower-http = { version = "0.5.2", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter", "time"]}
url = {workspace = true}
zstd = "0.13.2"
hyper-util = { version = "0.1.11", features = [
    "server",
    "http1",
    "http2",
    "tokio",
    "service",
]}
http-body-util = "0.1.2"
