[general]
realm_key = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAm0MmPVNon81HDfAXRXtCuS3msYVLVB8KqEAXrtoctMU=\n-----END PUBLIC KEY-----"
node_key = "358ea489d2f7d91466eff6edbb7d69b507346dc199d963915138865c03ffe1db"

[persistence]
path = "/tmp/node1/heed"

[backend]
backend_type = "S3" #"Postgres", "FS", "HTTP", "Memory", ...
encryption = false
compression = false
deduplication = false
# Schema which defines the path under which uploaded objects are stored
#backend_scheme = "{{NODE_ID}}/{{GROUP_ID}}/{{RAND:ULID}}/{{BUCKET}}/{{KEY}}"

[backend.access]
endpoint = "http://localhost:9000"
region = "eu-central-1"
disable_config_load = "true"
# Should access credentials and bucket be dynamically set ?
bucket = "aruna"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"

# FileSystem example config
#[backend.access]
#root = "/aruna"
#atomic_write_dir = /aruna/tmp

# PostgreSQL example config
#[backend.access]
#connection_string = "postgres://postgres:mysecretpassword@localhost:5432/test"
#table = "aruna"
#key_field = "path"
#value_field = "data"

# Http read-only example config
#[backend.access]
#endpoint = "https://zenodo.org"
#root = "records"

# In memory example config
#[backend.access]
#root = "/aruna"

[frontend.openapi_frontend]
address = "0.0.0.0"
port = 8085

[frontend.s3_frontend]
server = "0.0.0.0:1337"
hostname = "localhost:1337"
cors_exception = "http://localhost:3000"