[general]
realm_id = "01JWRB29J0Q2M3YTJGR24P5N31"

[persistence]
path = "/tmp/node1/heed"

[backend]
backend_type = "S3" # "FS", "PSQL", "HTTP", "Memory", ...
encryption = false
compression = false
deduplication = false

[backend.access]
endpoint = "http://localhost:9000"
region = "us-east-1"
# Should access credentials and bucket be dynamically set ?
bucket = "aruna"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"

# FileSystem example config
#[backend.access]
#root = "/aruna"
#atomic_write_dir = /aruna/tmp

# PostgreSQL example config
#[backend.access]
#root = /aruna
#connection_string = "postgres://postgres@localhost:5432/test"
#table = "objects"
#key_field = ""
#value_field = ""

[frontend.openapi_frontend]
address = "0.0.0.0"
port = 50056

[frontend.s3_frontend]
server = "0.0.0.0:1337"
hostname = "localhost:1337"
cors_exception = "http://localhost:3000"