pub mod access;
pub mod bucket;
pub mod listing;
pub mod multipart;
pub mod object;
pub mod policy_bulk;
pub mod policy_coverage;
pub mod policy_mutation;
pub mod policy_successor;
pub mod purge_fence;
pub mod session;
mod write_cleanup;

// Temporary re-exports of pre-family operation paths so existing callers keep
// compiling; remove once every consumer uses the family paths.
pub use crate::s3::access::create as create_access;
pub use crate::s3::access::get as get_access;
pub use crate::s3::access::list as list_access;
pub use crate::s3::access::revoke as revoke_access;
pub use crate::s3::bucket::cors as bucket_cors;
pub use crate::s3::bucket::create as create_bucket;
pub use crate::s3::bucket::delete as delete_bucket;
pub use crate::s3::bucket::forward;
pub use crate::s3::bucket::get as get_bucket;
pub use crate::s3::bucket::list as list_buckets;
pub use crate::s3::bucket::placement as bucket_placement;
pub use crate::s3::bucket::routing as bucket_routing;
pub use crate::s3::bucket::search as search_buckets;
pub use crate::s3::bucket::usage as bucket_usage;
pub use crate::s3::multipart::abort as abort_upload;
pub use crate::s3::multipart::complete as complete_upload;
pub use crate::s3::multipart::create as create_upload;
pub use crate::s3::multipart::part_copy as copy_part;
pub use crate::s3::multipart::part_upload as upload_part;
pub use crate::s3::multipart::parts as list_parts;
pub use crate::s3::multipart::uploads as list_uploads;
pub use crate::s3::object::attributes as get_attributes;
pub use crate::s3::object::copy as copy_object;
pub use crate::s3::object::delete as delete_object;
pub use crate::s3::object::delete_bulk as delete_objects;
pub use crate::s3::object::get as get_object;
pub use crate::s3::object::head as head_object;
pub use crate::s3::object::list as list_objects;
pub use crate::s3::object::metadata as refresh_metadata;
pub use crate::s3::object::placement as object_placement;
pub use crate::s3::object::put as put_object;
pub use crate::s3::object::search as search_objects;
pub use crate::s3::object::versions as list_versions;
