pub mod create_bucket;
pub mod create_user_access;
pub mod delete_bucket;
pub mod delete_object;
pub mod get_bucket_info;
pub mod get_object;
pub mod get_user_access;
pub mod list_buckets;
pub mod put_object;
