pub mod abort_upload;
mod access_index;
pub mod bucket_cors;
pub mod bucket_placement;
pub mod bucket_routing;
pub mod bucket_usage;
pub mod complete_upload;
pub mod copy_object;
pub mod copy_part;
pub mod create_access;
pub mod create_bucket;
pub mod create_upload;
pub mod delete_bucket;
pub mod delete_object;
pub mod delete_objects;
pub mod get_access;
pub mod get_attributes;
pub mod get_bucket;
pub mod get_object;
pub mod head_object;
pub mod list_access;
pub mod list_buckets;
pub mod list_objects;
pub mod list_parts;
pub mod list_uploads;
pub mod list_versions;
pub mod listing;
mod object_lookup;
pub mod object_placement;
pub mod policy_bulk;
pub mod policy_coverage;
pub mod policy_mutation;
pub mod policy_successor;
pub mod purge_fence;
pub mod put_object;
pub mod refresh_metadata;
pub mod revoke_access;
pub mod search_buckets;
pub mod search_objects;
pub mod session;
#[cfg(test)]
mod tests;
pub mod upload_part;
mod upload_target;
mod write_cleanup;
