[package]
name = "aruna_server"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.7.1"
milli = { git = "https://github.com/arunaengine/meilisearch.git"}
synevi = { git = "https://github.com/arunaengine/synevi.git", branch = "feat/refactor_wait_handler" }
aruna-rust-api = { git = "https://github.com/arunaengine/rust-api.git", branch = "feat/v3" }
serde = { version = "1.0.214", features = ["derive"] }
bincode = "1.3.3"
thiserror = "2.0.0"
ahash = "0.8.11"
ulid = { version = "1.1.3", features = ["serde"] }
tonic = { version = "0.12.3", features = ["tls", "tls-roots"] }
tokio = { version = "1.41.1", features = ["full", "tracing"] }
dotenvy = "0.15.7"
chrono = "0.4.38"
utoipa = { version = "5.2.0", features = ["chrono", "axum_extras", "ulid", "url"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
prost = "0.13.3"
axum = "0.8.1"
serde_json = "1.0.132"
tower-http = { version = "0.6.1", features = ["cors", "trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
console-subscriber = "0.4.1"
async-trait = "0.1.83"
base64 = "0.22.1"
jsonwebtoken = {git = "https://github.com/arunaengine/jsonwebtoken.git"}
sha2 = "0.10.8"
reqwest = { version = "0.12.9", features = ["json"] }
prost-wkt = "0.6"
prost-wkt-types = "0.6"
heed = "0.21.0"
typetag = "0.2.18"
obkv = "0.3.0"
roaring = "0.10.6"
url = { version = "2.5.3", features = ["serde"] }
utoipa-axum = "0.2.0"
axum-extra = {version = "0.10.0", features = ["query"]}
ed25519-dalek = { version = "2.1.1", features = ["pem"] }
curve25519-dalek = "4.1.3"
sha3 = { version = "0.10.8", features = ["std", "asm"] }
crypto_kx = "0.2.1"
hex = "0.4.3"

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
tonic = { version = "0.12.3", features = ["tls", "tls-roots"] }
prost-build = "0.13.3"
prost-wkt-build = "0.6"
